project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("social.core.urls")),
    path("invites/", include("social.invites.urls")),
    path("users/", include("social.users.urls")),
    path("accounts/", include("allauth.urls")),
    path("clubhouse/", admin.site.urls),
]

# Enable the debug toolbar only in DEBUG mode.
if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

social/core/urls.py
from django.urls import path

from social.core import views

app_name = "core"
urlpatterns = [path("", views.IndexView.as_view(), name="index")]

social/invites/urls.py
from django.urls import path

from . import views

app_name = "invites"
urlpatterns = [path("send/<str:username>/", views.send_invite, name="send_invite")]

social/users/urls.py
from django.urls import path

from social.users import views

app_name = "users"
urlpatterns = [path("<str:username>/", views.UserDetailView.as_view(), name="detail")]

social/invites/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Invite(models.Model):
    """An invitation from one user to another to establish a connection

    The invite counts against a user's max total connections
    if the invitation ends with no connection between users
    (i.e., rejected or expired).

    This behavior is a linchpin to help reduce abuse and spammy requests.
    """

    class InviteStatus(models.IntegerChoices):
        PENDING = 1
        SENT = 2
        ACCEPTED = 3
        REJECTED = 4
        EXPIRED = 5

    IN_FLIGHT_STATUSES = [InviteStatus.PENDING, InviteStatus.SENT]

    created_at = models.DateTimeField(auto_now_add=True)
    sent_at = models.DateTimeField(null=True, blank=True)
    from_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sent_invites"
    )
    to_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="received_invites",
    )
    status = models.IntegerField(
        choices=InviteStatus.choices, default=InviteStatus.PENDING
    )

    @classmethod
    def bulk_expire(cls, older_than):
        """Expire sent invites that are older than the provided datetime."""
        cls.objects.filter(status=cls.InviteStatus.SENT, sent_at__lt=older_than).update(
            status=cls.InviteStatus.EXPIRED
        )

    def send(self):
        """Send the invite via email.

        Note: This invokes email sending so it should be handled outside
        of the request/response lifecycle.
        """
        # TODO: Send the email.
        self.sent_at = timezone.now()
        self.status = self.InviteStatus.SENT
        self.save()

    def accept(self):
        """Accept an invite.

        The two users are connected.
        """
        # TODO: Create a connection.
        self.status = self.InviteStatus.ACCEPTED
        self.save()

    def reject(self):
        """Reject an invite."""
        self.status = self.InviteStatus.REJECTED
        self.save()

social/users/models.py
from django.contrib.auth.models import AbstractUser

from social.invites.models import Invite

from . import constants


class User(AbstractUser):
    """A custom user for extension"""

    @property
    def remaining_connections(self):
        """Get the number of remaining available connections."""
        return (
            constants.MAX_USER_CONNECTIONS
            - Invite.objects.filter(from_user=self)
            .exclude(status=Invite.InviteStatus.ACCEPTED)
            .count()
        )

social/invites/forms.py
from django import forms

from social.users.models import User

from . import constants
from .models import Invite


class SendInviteForm(forms.Form):
    """Set a pending a invite if valid."""

    from_user = forms.ModelChoiceField(
        queryset=User.objects.all(), required=True, widget=forms.HiddenInput()
    )
    to_user = forms.ModelChoiceField(
        queryset=User.objects.all(), required=True, widget=forms.HiddenInput()
    )

    def clean(self):
        cleaned_data = super().clean()
        from_user = cleaned_data.get("from_user")
        to_user = cleaned_data.get("to_user")

        self._check_user(from_user)
        self._check_user(to_user)
        self._check_max_connections(from_user)
        self._check_existing_invite(from_user, to_user)
        self._check_self_invite(from_user, to_user)
        self._check_in_flight_invites(from_user)

    def _check_user(self, user):
        if user is None:
            raise forms.ValidationError("The user is invalid.")

    def _check_max_connections(self, from_user):
        if from_user.remaining_connections <= 0:
            raise forms.ValidationError(
                "You are at your maximum number of connections."
            )

    def _check_existing_invite(self, from_user, to_user):
        if Invite.objects.filter(from_user=from_user, to_user=to_user).exists():
            raise forms.ValidationError("You have already sent an invitation.")

    def _check_self_invite(self, from_user, to_user):
        if from_user == to_user:
            raise forms.ValidationError(
                "You may not invite yourself. You're already here!"
            )

    def _check_in_flight_invites(self, from_user):
        if (
            Invite.objects.filter(
                from_user=from_user, status__in=Invite.IN_FLIGHT_STATUSES
            ).count()
            >= constants.MAX_IN_FLIGHT_INVITES
        ):
            raise forms.ValidationError(
                "You have too many sent invitations out currently."
            )

    def save(self):
        """Create a pending invite."""
        Invite.objects.create(
            from_user=self.cleaned_data["from_user"],
            to_user=self.cleaned_data["to_user"],
        )

social/core/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    def get_template_names(self):
        if self.request.user.is_authenticated:
            return ["core/index.html"]
        else:
            return ["core/landing.html"]

social/invites/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_http_methods

from social.users.models import User

from .forms import SendInviteForm


@login_required
@require_http_methods(["GET", "POST"])
def send_invite(request, username: str):
    """Send an invite to a new user.

    Creates a pending invite between users.
    """
    to_user = get_object_or_404(User, username=username)
    if request.method == "GET":
        form = SendInviteForm(
            data={"from_user": str(request.user.id), "to_user": str(to_user.id)}
        )
    else:
        form = SendInviteForm(data=request.POST)

    is_valid = form.is_valid()

    if request.method == "POST" and is_valid:
        form.save()
        messages.add_message(request, messages.SUCCESS, f"Invite sent to {username}.")
        return redirect("core:index")

    context: dict = {
        "form": form,
        "remaining_connections": request.user.remaining_connections,
        "to_user": to_user,
    }
    return render(request, "invites/send.html", context)

social/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView

from social.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # The view needs to deconflict with the user context
    # that the auth system injects to the context.
    context_object_name = "viewed_user"
    slug_field = "username"
    slug_url_kwarg = "username"

templates/app.html
{% extends "base.html" %}

{% block main_container %}
  <main class="container mx-auto p-8 flex-grow">
    {% include "messages.html" %}
    {% block main %}{% endblock %}
  </main>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US" class="bg-white subpixel-antialiased">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
  <title>{% block title %}{% endblock %} - Social Circle</title>
</head>
<body class="min-h-screen flex flex-col">

  {% include "nav.html" %}

  {% block main_container %}{% endblock %}

  <footer class="container mx-auto border-t border-purple-100 p-4 text-center text-sm text-gray-600">
    <span class="mx-1">&copy; {% now "Y" %} Matt Layman</span>
    <a href="" class="mx-1 hover:text-gray-900">About</a>
    <a href="" class="mx-1 hover:text-gray-900">Terms</a>
    <a href="" class="mx-1 hover:text-gray-900">Privacy</a>
    {% if user.is_authenticated %}
      <form class="inline" method="POST" action="{% url 'account_logout' %}">
        {% csrf_token %}
        <button class="mx-1 hover:text-gray-900" type="submit">Log Out</button>
      </form>
    {% endif %}
  </footer>
  {% block scripts %}{% endblock %}
</body>
</html>

templates/core/index.html
{% extends "app.html" %}

{% block main %}
  <h1>Index</h1>
{% endblock %}

templates/core/landing.html
{% extends "base.html" %}

{% block title %}A social network for your real connections{% endblock %}

{% block main_container %}
  <main class="p-8 max-w-xl mx-auto">
    {% include "messages.html" %}
    <h1 class="text-orange-600 text-5xl text-center font-light mb-6">500 Connections</h1>
    <p class="text-gray-700 font-light mb-4">
      In your real life social circle,
      how many people are you connected to?
    </p>
    <p class="text-gray-700 font-light mb-4">
      No, that guy you knew in one class in high school doesn't count.
      <i>Why?</i>
      Well, because you probably don't really care about the baby pictures
      of his new kid.
    </p>
    <p class="text-gray-700 font-light mb-4">
      What if there was a social network
      that recognized that your <i>real</i> social network isn't a group of 100k people
      that follow you?
    </p>
    <p class="text-gray-700 font-light mb-4">
      SocialCircle is that network.
    </p>
    <p class="text-gray-700 font-light mb-4">
      I believe so strongly
      that you should focus
      on the real network
      of people in your life
      that SocialCircle <i>intentionally</i> limits the size
      of a personal network
      to <span class="font-medium">500 connections</span>.
    </p>
    <p class="text-gray-700 font-light mb-4">
      You know something else that's annoying about social networks?
      <i>Nothing is stopping that guy from high school from trying to add you to his network!</i>
    </p>
    <p class="text-gray-700 font-light mb-4">
      On SocialCircle,
      if someone tries to add you to their network
      and you don't connect with them,
      it's a strike against <i>their</i> total connections.
    </p>
    <p class="text-gray-700 font-light mb-4">
      So,
      if you're looking for a social network
      that's for the people you really care about,
      check out SocialCircle today.
    </p>
    <div class="text-center my-8">
      <a href="{% url "account_signup" %}" class="bg-gradient-to-br from-orange-500 to to-orange-700 hover:from-orange-400 hover:to-orange-600 text-white font-semibold py-3 px-4 rounded focus:outline-none focus:shadow-outline">
        Sign Up
      </a>
    </div>
    <p class="text-gray-700 font-light mb-4">
      Matt Layman<br>
      Founder of SocialCircle
    </p>
  </main>
{% endblock %}

templates/invites/send.html
{% extends "app.html" %}

{% block title %}Send invite to {{ to_user }}{% endblock %}

{% block main %}
  <div class="mx-auto max-w-lg">
    <h1 class="text-4xl text-center font-semibold text-orange-600 mb-8 pb-2 border-b border-orange-600">Send invite to {{ to_user }}</h1>
    {% if form.errors %}
      {% for error in form.non_field_errors %}
        <p class="mb-8 text-gray-800">{{ error }}</p>
      {% endfor %}

      <div class="text-center">
        <button class="bg-gradient-to-br from-orange-500 to to-orange-700 text-white font-semibold py-3 px-4 rounded opacity-50 cursor-not-allowed">
          Send invite to {{ to_user.username }}
        </button>
      </div>
    {% else %}
      <form method="POST">
        {% csrf_token %}
        <p class="mb-4 text-gray-800">
          Do you want to invite {{ to_user }} to join your network?
        </p>
        <p class="mb-8 text-gray-800">
          You have {{ remaining_connections }} remaining connection{{ remaining_connections|pluralize }}
          to add to your network.
        </p>
        {{ form.from_user }}
        {{ form.to_user }}
        <div class="text-center">
          <button type="submit" class="bg-gradient-to-br from-orange-500 to to-orange-700 hover:from-orange-400 hover:to-orange-600 text-white font-semibold py-3 px-4 rounded focus:outline-none focus:shadow-outline">
            Send invite to {{ to_user.username }}
          </button>
        </div>
      </form>
    {% endif %}
  </div>
{% endblock %}

templates/messages.html
{% if messages %}
  <ul class="flex flex-row justify-center mx-4 -mt-4 mb-4 w-full">
    {% for message in messages %}
      <li class="bg-orange-100 border border-orange-200 text-orange-900 p-4 mx-2 rounded-lg shadow-sm font-light">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}

templates/nav.html
<nav class="flex bg-orange-100 text-orange-900 sm:h-16 items-center">
  <div class="w-full max-w-6xl relative mx-auto px-6">
    <div class="py-2 flex flex-col sm:flex-row sm:items-center">
      <a href="/" class="block sm:mr-4 py-2 flex items-center justify-center">
        <div class="h-12 w-12 bg-orange-600 rounded-full mr-2 flex items-center justify-center">
          <div class="h-8 w-8 bg-white rounded-full flex items-center justify-center">
            <div class="h-4 w-4 bg-orange-400 rounded-full"></div>
          </div>
        </div>
        <div class="text-xl uppercase tracking-wider font-light">Social<span class="text-orange-600">Circle</span></div>
      </a>
      <div class="flex-grow"></div>

      <div class="flex flex-row justify-around">
        {% if user.is_authenticated %}
          {% if user.is_staff %}
            <div class="hidden sm:block mr-4">
              <a class="hover:underline font-light" href="{% url "admin:index" %}">
                Clubhouse
              </a>
            </div>
          {% endif %}
        {% else %}
          <div>
            <a class="hover:underline font-light" href="{% url 'account_login' %}">Log In</a>
          </div>
          <div>
            <a class="hover:underline ml-0 sm:ml-4 my-2 font-light" href="{% url 'account_signup' %}">Sign Up</a>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</nav>
<div class="h-1 bg-gradient-to-r from-orange-400 via-red-500 to-orange-800 w-full"></div>

templates/users/user_detail.html
{% extends "app.html" %}

{% block title %}{{ viewed_user.username }}{% endblock %}

{% block main %}
  {% if viewed_user != user %}
    <div class="mx-auto max-w-sm text-center">
      <h1 class="text-4xl font-semibold text-orange-600 mb-8 pb-2 border-b border-orange-600">{{ viewed_user.username }}</h1>
      <p class="mb-8 text-gray-800">You are not connected to {{ viewed_user.username }}.</p>
      <p>
        <a href="{% url "invites:send_invite" viewed_user.username %}" class="bg-gradient-to-br from-orange-500 to to-orange-700 hover:from-orange-400 hover:to-orange-600 text-white font-semibold py-3 px-4 rounded focus:outline-none focus:shadow-outline">
          Send invite to {{ viewed_user.username }}
        </a>
      </p>
    </div>
  {% endif %}
{% endblock %}